stages:
  - build
  - deploy

build_extension:
  image: node:latest
  cache:
    paths:
      - node_modules/
  stage: build
  script:
    - wget https://github.com/tree-sitter/tree-sitter/releases/download/v0.25.2/tree-sitter-linux-x64.gz
    - gunzip tree-sitter-linux-x64.gz
    - chmod +x tree-sitter-linux-x64
    - mv tree-sitter-linux-x64 /usr/bin/tree-sitter
    - cd tools/vscode-extension
    - npm install
    - npx vsce package
  artifacts:
    paths:
      - tools/vscode-extension/charon-lang-*.vsix

publish_extension:
  image: bash:latest
  stage: deploy
  script:
    - apk add curl
    - FILE_PATH="$(find tools/vscode-extension/ -type f -name "charon-lang-*.vsix")"
    - FILE_NAME="$(basename $FILE_PATH)"
    - |
      curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file "$FILE_PATH" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/vscode_extension/${CI_COMMIT_SHA}/charon-lang-${CI_COMMIT_SHA}.vsix"